-- 테이블 삭제
drop table comment
CASCADE;

--테이블 생성
CREATE TABLE comment(
	articleSeq INT(10) UNSIGNED NOT NULL,
	commentGroupNo INT(10) UNSIGNED NOT NULL,
	commentShape VARCHAR(10) DEFAULT '' NOT NULL,
	commentSeq INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	status VARCHAR(255) DEFAULT 'published' NOT NULL,
	userId VARCHAR(255) NOT NULL,
	content VARCHAR(255) NOT NULL,
	readCount INT(10) UNSIGNED NOT NULL,
	createAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (commentSeq),
	FOREIGN KEY(articleSeq) REFERENCES article(articleSeq) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(fileSeq) REFERENCES file(fileSeq) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;