CREATE DATABASE crawling;

CREATE USER 'admin' IDENTIFIED BY 'secret';

GRANT ALTER, CREATE, INSERT, SELECT, DELETE, REFERENCES, UPDATE, DROP, EXECUTE, LOCK TABLES, INDEX
ON crawling.* TO 'admin';

FLUSH PRIVILEGES;

grant ALTER, CREATE, INSERT, SELECT, DELETE, REFERENCES, UPDATE, DROP, EXECUTE, LOCK TABLES, INDEX
ON test.* to 'username';

--utf8mb4
ALTER DATABASE crawling CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
